#!/bin/sh
MASTER_IP=$(curl -s http://$MASTER_UI |  grep title | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')
sed -i s/__MASTER__/$MASTER_IP/ /etc/hadoop/etc/hadoop/core-site.xml
cd /etc/hadoop
bin/hdfs datanode
