#!/bin/bash
GIT_DIR=$HOME/.cfg
DOTFILE_DIR=$HOME/.dotfiles
rm -rf $GIT_DIR
mkdir -p $DOTFILE_DIR
install_git_curl() {
    apt-get update -y
    apt-get --no-install-recommends install -y -q git curl
    apt-get clean
    apt-get autoclean
    rm /var/lib/apt/lists/*
}
if ! [ -x "$(command -v git)" ]; then
    install_git_curl
fi
git clone --bare https://github.com/twistedogic/dotfiles.git $GIT_DIR
function config {
  /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$DOTFILE_DIR $@
}
config checkout
cp -a $DOTFILE_DIR/. $HOME

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
