#!/bin/bash
GIT_DIR=$HOME/.cfg
DOTFILE_DIR=$HOME/.dotfiles
rm -rf $GIT_DIR
mkdir -p $DOTFILE_DIR
install_git_curl() {
    apt-get update -y
    apt-get --no-install-recommends install -y -q git curl ca-certificates
    apt-get clean
    apt-get autoclean
    rm /var/lib/apt/lists/*
}
if ! [ -x "$(command -v git)" ]; then
    install_git_curl
fi
if ! [ -x "$(command -v curl)" ]; then
    install_git_curl
fi
curl https://raw.githubusercontent.com/twistedogic/dotfiles/master/setup.sh | sh
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
