#!/bin/bash
apt-get update -y && \
apt-get install -y -q tmux curl vim-nox git locales \
ca-certificates net-tools && \
apt-get clean autoclean && \
apt-get autoremove --yes && \
rm -rf /var/lib/{apt,dpkg,cache,log}/

rm ~/.bashrc
git clone --bare https://github.com/twistedogic/dotfiles.git $HOME/.cfg
function config {
  /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@
}
mkdir -p ${HOME}/.config-backup
config checkout
if [ $? = 0  ]; then
  echo "Checked out config.";
else
  echo "Backing up pre-existing dot files.";
  config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} ${HOME}/.config-backup/{}
fi;
config checkout
config config status.showUntrackedFiles no

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen