## start with the latest ubuntu
FROM dockerfile/elasticsearch

## That's me
MAINTAINER twistedogic

RUN /elasticsearch/bin/plugin -i elasticsearch/marvel/latest

CMD ["/elasticsearch/bin/elasticsearch"]


